name: Build

on:
  workflow_call:
    inputs:
      build_type:
        description: Type of build (Debug, Release, RelWithDebInfo, MinSizeRel)
        type: string
        default: Debug
      is_qt_cached:
        description: Enable Qt caching or not
        type: string
        default: true
    secrets:
      SPARKLE_ED25519_KEY:
        description: Private key for signing Sparkle updates
        required: false
      WINDOWS_CODESIGN_CERT:
        description: Certificate for signing Windows builds
        required: false
      WINDOWS_CODESIGN_PASSWORD:
        description: Password for signing Windows builds
        required: false
      APPLE_CODESIGN_CERT:
        description: Certificate for signing macOS builds
        required: false
      APPLE_CODESIGN_PASSWORD:
        description: Password for signing macOS builds
        required: false
      APPLE_CODESIGN_ID:
        description: Certificate ID for signing macOS builds
        required: false
      APPLE_NOTARIZE_APPLE_ID:
        description: Apple ID used for notarizing macOS builds
        required: false
      APPLE_NOTARIZE_TEAM_ID:
        description: Team ID used for notarizing macOS builds
        required: false
      APPLE_NOTARIZE_PASSWORD:
        description: Password used for notarizing macOS builds
        required: false
      GPG_PRIVATE_KEY:
        description: Private key for AppImage signing
        required: false
      GPG_PRIVATE_KEY_ID:
        description: ID for the GPG_PRIVATE_KEY, to select the signing key
        required: false

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            name: "Linux-Qt5"
            qt_ver: 5
            qt_host: linux
            qt_arch: ""
            qt_version: "5.15.2"
            qt_modules: "qtnetworkauth"

          - os: ubuntu-22.04
            name: "Linux-Qt6"
            qt_ver: 6
            qt_host: linux
            qt_arch: ""
            qt_version: "6.5.3"
            qt_modules: "qt5compat qtimageformats qtnetworkauth"

    runs-on: ${{ matrix.os }}

    env:
      INSTALL_DIR: "install"
      INSTALL_PORTABLE_DIR: "install-portable"
      BUILD_DIR: "build"
      CCACHE_VAR: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup ccache
        if: runner.os == 'Linux' && inputs.build_type == 'Debug'
        uses: hendrikmuhs/ccache-action@v1.2.17
        with:
          key: ${{ matrix.os }}-qt${{ matrix.qt_ver }}-${{ matrix.architecture }}

      - name: Use ccache on Debug builds only
        if: inputs.build_type == 'Debug'
        shell: bash
        run: |
          echo "CCACHE_VAR=ccache" >> $GITHUB_ENV

      - name: Set short version
        shell: bash
        run: |
          ver_short=`git rev-parse --short HEAD`
          echo "VERSION=$ver_short" >> $GITHUB_ENV

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y update
          sudo apt-get -y install ninja-build extra-cmake-modules scdoc libxcb-cursor-dev

      - name: Install Qt (Linux)
        if: runner.os == 'Linux'
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: "==3.1.*"
          py7zrversion: ">=0.20.2"
          version: ${{ matrix.qt_version }}
          host: ${{ matrix.qt_host }}
          target: "desktop"
          arch: ${{ matrix.qt_arch }} 
          modules: ${{ matrix.qt_modules }}
          cache: ${{ inputs.is_qt_cached }}

      - name: Configure CMake (Linux)
        if: runner.os == 'Linux'
        run: |
          cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DENABLE_LTO=ON -DLauncher_ENABLE_JAVA_DOWNLOADER=ON -DLauncher_BUILD_PLATFORM=official -DCMAKE_C_COMPILER_LAUNCHER=${{ env.CCACHE_VAR }} -DCMAKE_CXX_COMPILER_LAUNCHER=${{ env.CCACHE_VAR }} -DLauncher_QT_VERSION_MAJOR=${{ matrix.qt_ver }} -DLauncher_BUILD_ARTIFACT=Linux-Qt${{ matrix.qt_ver }} -G Ninja

      - name: Build
        if: runner.os == 'Linux'
        run: |
          cmake --build ${{ env.BUILD_DIR }}

      - name: Test
        if: runner.os == 'Linux'
        run: |
          ctest -E "^example64|example$" --test-dir build --output-on-failure

      - name: Package (Linux, portable)
        if: runner.os == 'Linux'
        run: |
          rm -rf ${{ env.BUILD_DIR }}/*
          cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PORTABLE_DIR }} -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DENABLE_LTO=ON -DLauncher_BUILD_PLATFORM=official -DCMAKE_C_COMPILER_LAUNCHER=${{ env.CCACHE_VAR }} -DCMAKE_CXX_COMPILER_LAUNCHER=${{ env.CCACHE_VAR }} -DLauncher_QT_VERSION_MAJOR=${{ matrix.qt_ver }} -DLauncher_BUILD_ARTIFACT=Linux-Qt${{ matrix.qt_ver }} -DINSTALL_BUNDLE=full -G Ninja
          cmake --build ${{ env.BUILD_DIR }}
          cmake --install ${{ env.BUILD_DIR }}
          cmake --install ${{ env.BUILD_DIR }} --component portable

          mkdir -p ${{ env.INSTALL_PORTABLE_DIR }}/lib
          cp /lib/x86_64-linux-gnu/libbz2.so.1.0* ${{ env.INSTALL_PORTABLE_DIR }}/lib/ || true
          cp /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0* ${{ env.INSTALL_PORTABLE_DIR }}/lib/ || true
          cp /usr/lib/x86_64-linux-gnu/libcrypto.so.* ${{ env.INSTALL_PORTABLE_DIR }}/lib/ || true
          cp /usr/lib/x86_64-linux-gnu/libssl.so.* ${{ env.INSTALL_PORTABLE_DIR }}/lib/ || true
          cp /usr/lib/x86_64-linux-gnu/libffi.so.*.* ${{ env.INSTALL_PORTABLE_DIR }}/lib/ || true
          
          find ${{ env.INSTALL_PORTABLE_DIR }}/bin -name "*.so*" -exec mv {} ${{ env.INSTALL_PORTABLE_DIR }}/lib \; || true

          for l in $(find ${{ env.INSTALL_PORTABLE_DIR }} -type f); do l=${l#$(pwd)/}; l=${l#${{ env.INSTALL_PORTABLE_DIR }}/}; l=${l#./}; echo $l; done > ${{ env.INSTALL_PORTABLE_DIR }}/manifest.txt
          cd ${{ env.INSTALL_PORTABLE_DIR }}
          tar -czf ../PrismLauncher-portable-Qt${{ matrix.qt_ver }}.tar.gz *

      - name: Upload binary tarball (Linux, portable, Qt 5)
        if: runner.os == 'Linux' && matrix.qt_ver == 5
        uses: actions/upload-artifact@v4
        with:
          name: PrismLauncher-Linux-Qt5-Portable-${{ env.VERSION }}-${{ inputs.build_type }}
          path: PrismLauncher-portable-Qt5.tar.gz

      - name: Upload binary tarball (Linux, portable, Qt 6)
        if: runner.os == 'Linux' && matrix.qt_ver == 6
        uses: actions/upload-artifact@v4
        with:
          name: PrismLauncher-Linux-Qt6-Portable-${{ env.VERSION }}-${{ inputs.build_type }}
          path: PrismLauncher-portable-Qt6.tar.gz
